### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by P1agueDoc** [lawrencea13/LethalCompanyGameMaster#1]
Sorry for writing this as a issue. But I would like to ask, do you know how to change the music on the boombox and the video on the TV?

**Comment by lawrencea13** [comment]
We could look towards https://github.com/u-2018/LC-API and use the asset loading function to load in a video and/or sound. Then you can either override the constructors or something else on a boombox item or TV item. In practice I'm not 100% sure, I haven't tried to do any sort of asset bundle loading.

**Comment by P1agueDoc** [comment]
thanks I'll try
