### ISSUE TITLE
mods bug

### ISSUE THREAD

**Issue by drink1101** [lawrencea13/LethalCompanyGameMaster#15]
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/a97a5f33-3690-4f38-8059-609b1adf57c9)
open the game and creating a new save will show like but if you quit and create another one it will be fixed, im not using and funtion about deadline or quota and this is only mod that i installed

**Comment by lawrencea13** [comment]
If you’re referring to the deadline, that appears to be infinite deadline being turned on. If not, could you be a bit more specific?

**Comment by drink1101** [comment]
> If you’re referring to the deadline, that appears to be infinite deadline being turned on. If not, could you be a bit more specific?

yeah the problem is that I didn't turn on any of these functions, so you open the game create a new save, and it will show like this 
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/a0db0573-8a28-42be-86de-8e4f34686db7)
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/9b61ea9e-ebe0-4805-97e0-781d47de4435)
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/81fca058-0342-4d20-bcc1-42f9c2f387d3)


and if you choose to land the game will stuck like this 
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/a80a1e3f-cd36-421c-9214-c310827712ec)

I found two doable solutions, you can quit to the main menu and enter the save again it will show like this 
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/4d48c6ef-ce65-431a-a0d7-ae4943bb9332)

or you could go to the company first land and take off.
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/8e2773bf-7222-4ab6-b0ed-20055960757f)
![image](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/85337928/533dd3b3-7288-40e8-9c47-175cdfb675b7)

I think it is the game update causing this bug because I tried to only use this mod and still have the same problem.

**Comment by lawrencea13** [comment]
The mod hasn’t been updated since like v40 so that’s probably why. I’m doing a full rewrite anyway so when it’s released for the current version, it should be significantly better. 

https://youtu.be/1U3cjSQvjkQ?si=RzuxZ_H-kelzm3rF
