### ISSUE TITLE
My insert doesnt work, can i change the key to open the menu?

### ISSUE THREAD

**Issue by Pizzakopf** [lawrencea13/LethalCompanyGameMaster#16]
LIke it says in the tilte, my insert key doesnt work and no i wanted to ask if there is any way to change the key that opens the menu?

**Comment by lawrencea13** [comment]
The mod is a bit out of date and needs to be updated. I’m doing a full rewrite that resolves this issue in the future. See: https://youtu.be/1U3cjSQvjkQ?si=5cZuu19gkxOMhbHZ

**Comment by Pizzakopf** [comment]
THANK YOU SO MUCH FOR TELLING ME!
CAN YOU PLEASE MAYBE SOMEHOW NOTIFY ME WHEN THE UPDATE IS RELEASED???

lawrencea13 ***@***.***> schrieb am Fr., 12. Jan. 2024, 22:20:

**Comment by cluzier** [comment]
> The mod is a bit out of date and needs to be updated. I’m doing a full rewrite that resolves this issue in the future. See: https://youtu.be/1U3cjSQvjkQ?si=5cZuu19gkxOMhbHZ

Any way some of us could beta test? Fellow developer here and would love to assist on the rewrite to ensure LC players playing via Whisky on MacOS devices are able to view the GUI without issues. Currently I've ran into an issue where GUI's are not displaying the text on buttons in the menus or the insert key is not available on Mac devices so to allow for another keybind to open the menu.

**Comment by lawrencea13** [comment]
Absolutely, reach out on discord: iminx

**Comment by cluzier** [comment]
> Absolutely, reach out on discord: iminx 

I sent you a request. I am xer6131

**Comment by lawrencea13** [comment]
I incorrectly spelt my name, I sent a request. It is iminxx not iminx.
