### ISSUE TITLE
Game Master breaks the game *see description*

### ISSUE THREAD

**Issue by angermanaged** [lawrencea13/LethalCompanyGameMaster#18]
cannot launch ship.... just does nothing after pulling lever, stuck on 7 days 3 hours, lots of errors, terminal text out of place. will send logs and screenshot of issues as best i can.

![Screenshot (18)](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/81065551/b33a1b6a-80fc-4199-acbf-68d72d51fb51)
![Screenshot (17)](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/81065551/79f51817-d940-4c95-b14f-4bbbaf1dcf30)
![Screenshot (16)](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/81065551/5d73558f-bded-44d1-a78a-7d5ea120d60f)
![Screenshot (14)](https://github.com/lawrencea13/LethalCompanyGameMaster/assets/81065551/bfedf683-2b24-4813-bff3-5df3e89e1733)
[Player.log](https://github.com/lawrencea13/LethalCompanyGameMaster/files/13996247/Player.log)

**Comment by angermanaged** [comment]
i am so sorry about the name of my pc my friend made that i cant change it. it stuck with n-word i just realized it was on screen

**Comment by lawrencea13** [comment]
This version is old and hasn't been updated since v40, please see early access for re-release here: https://github.com/lawrencea13/GameMaster2.0
