### ISSUE TITLE
would hotkeys be possible?

### ISSUE THREAD

**Issue by Ekko9559** [lawrencea13/LethalCompanyGameMaster#2]
would I be able to put commands like speed, god, or nigh vision on a hotkey instead of having to do a / command in chat?

**Comment by lawrencea13** [comment]
Not in the current version, it's on the list of things I'm adding either in the update coming out today or in the next one

**Comment by Ekko9559** [comment]
thank you for the quick response 

> Not in the current version, it's on the list of things I'm adding either in the update coming out today or in the next one
