### ISSUE TITLE
Patched mono

### ISSUE THREAD

**Issue by P1agueDoc** [lawrencea13/LethalCompanyGameMaster#3]
I'd like to ask. Have you patched the mono dll? (Lethal Company\MonoBleedingEdge\EmbedRuntime) 
If so, can you please share them? I tried to patch them but I can't find the git hash of the mono version for this game

**Comment by lawrencea13** [comment]
I did not match anything in there. Everything I patched is in Lethal Company\Lethal Company_Data\Managed and just about 99% of it is in Assembly-CSharp.dll

**Comment by P1agueDoc** [comment]
thanks for the answer
